(header-menu (@ (root-href "https://registers.app/")
                (selected "Blog")
                (links (
                  ("https://registers.app/explore" "Explore")
                  ("https://registers.app/features" "Why Registers?")
                  ("https://registers.app/enterprise" "Enterprise")
                  ("https://registers.app/pricing" "Pricing")
                  ("{{ site.baseurl }}" "Blog")
                  ("https://registers.app/login" "Start now")
                ))))